!--------------------------------------------------------------------------------------------------
!  FILE chem_data_fc.f90
!  Module for chemical kinetics in NGA2 (finite chemistry)
!  Generated by yaml2nga.py from a YAML mechanism. Do not edit manually.
!  Source: skeleton.yaml
!  Reverse rates: detailed balance at run time (k_r = k_f/K_c, K_c from the NASA7 table)
!--------------------------------------------------------------------------------------------------

module fcmech
  use precision
  use string
  implicit none

  !--------------------------------------------------------------------------------------------------
  !  VARIABLE DEFINITIONS (SI units: m, s, mol, J, K, Pa)
  !--------------------------------------------------------------------------------------------------
  !  Rcst, P_ref    : universal gas constant (J/(mol K)), standard-state pressure of the thermo data (Pa)
  !  nS, nR, nA     : number of species, of one-directional rates w(i), of atom types
  !  sXXX           : species index (1..nS) for species XXX
  !  W_sp           : molar mass (kg/mol), dimension(nS)
  !  atom_names, atom_masses, comp_matrix(a,s) : atoms, their molar masses (kg/mol), count of atom a in species s
  !  koveps         : 1/(eps/k) for Lennard-Jones (1/K), dimension(nS); T* = T*koveps
  !  mucoeff        : viscosity prefactor, mu = mucoeff*sqrt(T)/Omega_mu(T*), dimension(nS)
  !  Dcoeffs        : binary diffusion prefactor, D_ij = Dcoeffs*T^1.5/(P*Omega_D), dimension(nS,nS)
  !  Ocoeffs        : sqrt(koveps_i*koveps_j) giving T* for the pair, dimension(nS,nS)
  !  Cpsp, hsp      : species Cp (J/(mol K)) and enthalpy (J/mol), dimension(nS), set by fcmech_thermodata
  !  T_mid          : NASA7 switch temperature (K), dimension(nS)
  !  thermo_coeffs  : NASA7 coefficients, dimension(nS,14): cols 1-7 low T (a1..a7), cols 8-14 high T
  !  k(1:nR), w(1:nR) layout (every reversible reaction has a forward and a reverse entry):
  !     1..n_arr_fwd             Arrhenius forward          n_arr_fwd+1..i_arr_end   Arrhenius reverse
  !     i_arr_end+1..i_tb_end    three-body forward         ..i_tb_bwd_end           three-body reverse
  !     i_tb_bwd_end+1..i_fo_end falloff forward            ..i_fo_bwd_end           falloff reverse
  !     i_plog_start..i_plog_end PLOG forward               i_plog_bwd_start..i_plog_bwd_end PLOG reverse
  !  Reverse rates: see the header line above (run-time detailed balance, or Arrhenius fits of k_f/K_c
  !     stored after the forward parameters: ln_A_arr(n_arr_fwd+1:n_arr), *_tb_b, *_b_fo, *_b_plog).
  !  ln_A_*, b_*, E_R_*  : Arrhenius parameters ln(A) [SI], temperature exponent, Ea/R (K)
  !  A_sign_*            : sign of A (present only if the mechanism uses negative-A reactions)
  !  Troe_a,Troe_T3,Troe_T1,Troe_T2 : Troe parameters (Lindemann: a=1, T3=T1=1e30; T2=1e30 if absent)
  !  n_m, default_eff, n_eff, eff_species_idx, eff_matrix_reduced : third-body groups
  !     M(g) = default_eff(g)*(sum(c) - sum(c_eff)) + eff_matrix_reduced(g,:).c_eff; reactions with identical
  !     efficiency sets share a group (fo_m_idx(i) = group of falloff reaction i)
  !  P_plog, ln_P_plog, ln_A_plog, b_plog, E_R_plog, plog_reac_start, plog_reac_len : PLOG tables (P in Pa)
  !  n_rev, rev_fwd_w, rev_bwd_w : reversible reactions and the w indices of their forward/reverse rates;
  !     get_production_rates sums them as net rates w(fwd) - w(rev); get_destruction_rates sums the
  !     one-directional rates consuming each species (fcmech_get_ydot_ddot returns both in mass units)
  !  fo_rev_src, plog_rev_src, kcinv_cache : falloff/PLOG reverse rates are k_f(src) * kcinv(T)
  !  *_cache : temperature-only data (k(T), falloff limits, F_cent, NASA7) kept from the previous call and
  !     reused while T (and P for PLOG) is unchanged; exact comparison; threadprivate under OpenMP
  !  fcmech_vexp : vectorizable exp used for all rate-coefficient exponentials (relative error < 1e-14)
  !--------------------------------------------------------------------------------------------------

  real(WP), parameter :: Rcst = 8.314462618_WP
  real(WP), parameter :: P_ref = 101325.0_WP
  integer, parameter :: nS = 3
  integer, parameter :: nR = 2
  integer, parameter :: nA = 2

  ! --- Species indices ---
  integer, parameter :: sO2 = 1
  integer, parameter :: sO = 2
  integer, parameter :: sN2 = 3

  ! --- Molar masses (kg/mol) ---
  real(WP), parameter, dimension(nS) :: W_sp = [ &
       0.031998_WP, 0.015999_WP, 0.028014_WP ]  ! O2, O, N2

  ! --- Atoms: names, molar masses (kg/mol), composition comp_matrix(a,s) ---
  character(len=2), parameter, dimension(nA) :: atom_names = [ &
       'O ', 'N ' ]
  real(WP), parameter, dimension(nA) :: atom_masses = [ &
       0.015999_WP, 0.014007_WP ]  ! O, N
  integer, parameter, dimension(nA,nS) :: comp_matrix = reshape([ &
       2, 0, 1, 0, 0, 2 ], shape=[nA,nS])

  ! --- Transport (Lennard-Jones / Chapman-Enskog, Neufeld collision integrals) ---
  real(WP), parameter, dimension(nS) :: koveps = [ &
       0.009310986964618248_WP, 0.0125_WP, 0.010253255408592227_WP ]  ! O2, O, N2
  real(WP), parameter, dimension(nS) :: mucoeff = [ &
       1.2613932275530575e-06_WP, 1.411959718575362e-06_WP, 1.0782307084944052e-06_WP ]  ! O2, O, N2
  ! nS x nS pair tables: DATA-initialized protected variables (a parameter array constructor is
  ! limited to 65535 elements, i.e. 255 species)
  real(WP), protected, dimension(nS,nS) :: Dcoeffs
  data Dcoeffs(1:3,1) / &
       1.0_WP, 0.0005981604716219653_WP, 0.00038887073040051555_WP /
  data Dcoeffs(1:3,2) / &
       0.0005981604716219653_WP, 1.0_WP, 0.0005818075329378441_WP /
  data Dcoeffs(1:3,3) / &
       0.00038887073040051555_WP, 0.0005818075329378441_WP, 1.0_WP /
  real(WP), protected, dimension(nS,nS) :: Ocoeffs
  data Ocoeffs(1:3,1) / &
       1.0_WP, 0.010788296300052576_WP, 0.009770769030854418_WP /
  data Ocoeffs(1:3,2) / &
       0.010788296300052576_WP, 1.0_WP, 0.011321028778666841_WP /
  data Ocoeffs(1:3,3) / &
       0.009770769030854418_WP, 0.011321028778666841_WP, 1.0_WP /

  ! --- Thermodynamics: Cp and enthalpy (module variables, set by fcmech_thermodata) ---
  real(WP), dimension(nS) :: Cpsp, hsp

  ! --- NASA7 thermo: switch temperature (K) and coefficients (low cols 1-7, high cols 8-14) ---
  real(WP), parameter, dimension(nS) :: T_mid = [ &
       1000.0_WP, 1000.0_WP, 1000.0_WP ]  ! O2, O, N2
  real(WP), parameter, dimension(nS,14) :: thermo_coeffs = reshape([ &
       3.78245636_WP, 3.1682671_WP, 3.298677_WP, -0.00299673416_WP, &
       -0.00327931884_WP, 0.0014082404_WP, 9.84730201e-06_WP, 6.64306396e-06_WP, &
       -3.963222e-06_WP, -9.68129509e-09_WP, -6.12806624e-09_WP, 5.641515e-09_WP, &
       3.24372837e-12_WP, 2.11265971e-12_WP, -2.444854e-12_WP, -1063.94356_WP, &
       29122.2592_WP, -1020.8999_WP, 3.65767573_WP, 2.05193346_WP, &
       3.950372_WP, 3.28253784_WP, 2.56942078_WP, 2.92664_WP, &
       0.00148308754_WP, -8.59741137e-05_WP, 0.0014879768_WP, -7.57966669e-07_WP, &
       4.19484589e-08_WP, -5.68476e-07_WP, 2.09470555e-10_WP, -1.00177799e-11_WP, &
       1.0097038e-10_WP, -2.16717794e-14_WP, 1.22833691e-15_WP, -6.753351e-15_WP, &
       -1088.45772_WP, 29217.5791_WP, -922.7977_WP, 5.45323129_WP, &
       4.78433864_WP, 5.980528_WP ], shape=[nS,14])

  ! --- Reaction counts and k/w index boundaries ---
  integer, parameter :: n_arr_fwd = 0, n_arr_rev = 0, n_arr = 0
  integer, parameter :: n_tb = 1, n_tb_rev = 1
  integer, parameter :: n_fo = 0, n_fo_rev = 0
  integer, parameter :: n_plog = 0, n_plog_rev = 0, n_plog_pts = 0
  integer, parameter :: n_m = 1  ! third-body/falloff M groups
  integer, parameter :: i_arr_end = 0, i_tb_end = 1, i_tb_bwd_end = 2
  integer, parameter :: i_fo_end = 2, i_fo_bwd_end = 2
  integer, parameter :: i_plog_start = 3, i_plog_end = 2
  integer, parameter :: i_plog_bwd_start = 3, i_plog_bwd_end = 2

  ! --- Three-body: ln(A), b, E/R ---
  real(WP), parameter, dimension(n_tb) :: ln_A_tb = [ &
       11.695247021764184_WP ]
  real(WP), parameter, dimension(n_tb) :: b_tb = [ &
       -1.0_WP ]
  real(WP), parameter, dimension(n_tb) :: E_R_tb = [ &
       0.0_WP ]

  ! --- Third-body efficiencies: species with explicit efficiencies ---
  integer, parameter :: n_eff = 2
  integer, parameter, dimension(n_eff) :: eff_species_idx = [ &
       3, 1 ]  ! N2, O2
  real(WP), parameter, dimension(n_m,n_eff) :: eff_matrix_reduced = reshape([ &
       1.0_WP, 1.0_WP ], shape=[n_m,n_eff])
  real(WP), parameter, dimension(n_m) :: default_eff = [ &
       1.0_WP ]

  integer, parameter :: n_rev = 1  ! reversible reactions
  integer, parameter :: n_kcinv = 0  ! falloff + PLOG reverse rates evaluated as k_f * kcinv(T)
  ! --- w indices of the forward and reverse rate of each reversible reaction (net rate = w(fwd) - w(rev)) ---
  integer, parameter, dimension(n_rev) :: rev_fwd_w = [ &
       1 ]
  integer, parameter, dimension(n_rev) :: rev_bwd_w = [ &
       2 ]

  ! --- Caches of temperature-dependent data, reused by calls at the same T (Newton iterations, finite-
  !     difference Jacobian columns that perturb the composition only); PLOG data are keyed on (T,P).
  !     The exact comparisons on T and P are intentional. Serial use, or per-thread with OpenMP through
  !     the threadprivate directive below. ---
  real(WP), save :: T_nasa_cache = -1.0_WP
  real(WP), dimension(nS), save :: cp_R_cache, h_RT_cache, s_R_cache
  real(WP), save :: T_rate_cache = -1.0_WP
  real(WP), save :: P_rate_cache = -1.0_WP
  real(WP), dimension(nR), save :: k_T_cache  ! Arrhenius/three-body (forward and reverse) and PLOG forward k
  !$omp threadprivate(T_nasa_cache, cp_R_cache, h_RT_cache, s_R_cache)
  !$omp threadprivate(T_rate_cache, P_rate_cache, k_T_cache)

  contains

  ! Reduced collision integral Omega^(2,2)* for viscosity (Neufeld et al. 1972 rational fit)
  real(WP) function fcmech_omegamu(T_)
    implicit none
    real(WP), intent(in) :: T_  ! reduced temperature T* = T*k/eps
    real(WP), parameter, dimension(9) :: mArray = [ &
         3.3530622607_WP, 2.53272006_WP, 2.9024238575_WP, &
         0.11186138893_WP, 0.8662326188_WP, 1.3913958626_WP, &
         3.158490576_WP, 0.18973411754_WP, 0.00018682962894_WP ]
    integer :: i
    real(WP) :: num, den
    den = mArray(9)
    do i = 1, 4
      den = mArray(9-i) + T_*den
    end do
    num = mArray(4)
    do i = 1, 3
      num = mArray(4-i) + T_*num
    end do
    fcmech_omegamu = num/den
  end function fcmech_omegamu

  ! Reduced collision integral Omega^(1,1)* for diffusion (Neufeld et al. 1972 rational fit)
  real(WP) function fcmech_omegaD(T_)
    implicit none
    real(WP), intent(in) :: T_  ! reduced temperature T* = T*k/eps
    real(WP), parameter, dimension(9) :: mArray = [ &
         6.8728271691_WP, 9.4122316321_WP, 7.7442359037_WP, &
         0.23424661229_WP, 1.45337701568_WP, 5.2269794238_WP, &
         9.7108519575_WP, 0.46539437353_WP, 0.00041908394781_WP ]
    integer :: i
    real(WP) :: num, den
    den = mArray(9)
    do i = 1, 4
      den = mArray(9-i) + T_*den
    end do
    num = mArray(4)
    do i = 1, 3
      num = mArray(4-i) + T_*num
    end do
    fcmech_omegaD = num/den
  end function fcmech_omegaD

  !--------------------------------------------------------------------------------------------------
  !  function getlindratecoeff: pressure-dependent rate coefficient (Lindemann / Troe blending)
  !  k = kinf * F * Pr/(1+Pr), Pr = k0*M/kinf, log10 F = log10 Fcent / (1 + ((log10 Pr + c)/(n - d*(log10 Pr + c)))^2)
  !--------------------------------------------------------------------------------------------------
  real(WP) function getlindratecoeff(k0,kinf,fc,conc)
    implicit none
    ! k0, kinf : low-P and high-P rate coefficients (> 0)
    ! fc       : Troe centering factor F_cent (1 for Lindemann); clamped to a tiny positive value like Cantera
    ! conc     : third-body concentration M (mol/m^3); M <= 0 gives k = 0 (no fallback to P/(R*T))
    real(WP), intent(in) :: k0,kinf,fc,conc
    real(WP), parameter :: ln10 = 2.302585092994046_WP
    real(WP) :: redP,lgfc,ntmp,ccoeff,lgPr,f
    redP = k0 * MAX(conc, 0.0_WP) / MAX(kinf, TINY(1.0_WP))
    if (redP <= 0.0_WP) then
      getlindratecoeff = 0.0_WP
      return
    end if
    lgfc = LOG10(MAX(fc, 1.0e-300_WP))  ! same clamp as Cantera (Fcent <= 0 is possible with odd Troe data)
    ntmp = 0.75_WP - 1.27_WP*lgfc
    ccoeff = -0.4_WP - 0.67_WP*lgfc
    lgPr = LOG10(redP)
    f = (lgPr + ccoeff)/(ntmp - 0.14_WP*(lgPr + ccoeff))
    f = exp(ln10*lgfc/(f*f + 1.0_WP))
    getlindratecoeff = kinf * f * redP/(1.0_WP + redP)
  end function getlindratecoeff

  ! Effective third-body concentrations M(r) = default_eff(r)*sum_{i not in eff}(c_i) + sum_{j in eff} eff(r,j)*c_j
  subroutine get_thirdbodies(M,c)
    implicit none
    real(WP), dimension(nS), intent(in) :: c   ! species concentrations (mol/m^3)
    real(WP), dimension(n_m), intent(out) :: M  ! third-body concentration per reaction (mol/m^3)
    real(WP), dimension(n_eff) :: c_eff
    real(WP) :: sum_c_rest
    integer :: j
    do j = 1, n_eff
      c_eff(j) = c(eff_species_idx(j))
    end do
    sum_c_rest = sum(c) - sum(c_eff)
    M(:) = default_eff(:) * sum_c_rest + matmul(eff_matrix_reduced, c_eff)
  end subroutine get_thirdbodies

  !--------------------------------------------------------------------------------------------------
  !  subroutine fcmech_vexp: y = exp(x) for whole arrays, written so the compiler can SIMD-vectorize
  !  it (libm exp is scalar): Cody-Waite range reduction, degree-11 Taylor polynomial, exponent
  !  assembly. Relative error < 1e-14. Arguments are clamped to [-708, 709], so there is never an
  !  Inf/NaN; results below ~1e-307 are inexact (rates that are zero for any practical purpose).
  !--------------------------------------------------------------------------------------------------
  pure subroutine fcmech_vexp(x, y)
    implicit none
    real(WP), dimension(:), intent(in) :: x
    real(WP), dimension(:), intent(out) :: y
    integer, parameter :: dp = selected_real_kind(15, 307)  ! the algorithm needs IEEE double internally
    real(dp), parameter :: ln2_hi = 6.93147180369123816490e-01_dp, ln2_lo = 1.90821492927058770002e-10_dp
    real(dp), parameter :: inv_ln2 = 1.44269504088896338700_dp
    real(dp) :: xc, r, p
    integer(8) :: n
    integer :: i
    do i = 1, size(x)
      xc = min(max(real(x(i), dp), -708.0_dp), 709.0_dp)
      n = nint(xc*inv_ln2, 8)
      r = (xc - real(n, dp)*ln2_hi) - real(n, dp)*ln2_lo
      p = 1.0_dp + r*(1.0_dp + r*(0.5_dp + r*(1.0_dp/6.0_dp + r*(1.0_dp/24.0_dp + r*(1.0_dp/120.0_dp &
        + r*(1.0_dp/720.0_dp + r*(1.0_dp/5040.0_dp + r*(1.0_dp/40320.0_dp + r*(1.0_dp/362880.0_dp &
        + r*(1.0_dp/3628800.0_dp + r*(1.0_dp/39916800.0_dp)))))))))))
      y(i) = real(p*transfer(ishft(n + 1023_8, 52), 1.0_dp), WP)
    end do
  end subroutine fcmech_vexp

  !--------------------------------------------------------------------------------------------------
  !  subroutine get_rate_coefficients: k(1:nR) at (T,P), forward and reverse. Everything that depends
  !  on T only (and on P for PLOG) comes from the caches, refreshed when T (or P) changes; only the
  !  falloff blending with the third-body concentration is evaluated on every call.
  !--------------------------------------------------------------------------------------------------
  subroutine get_rate_coefficients(k,M,Tloc,Ploc)
    implicit none
    real(WP), dimension(nR), intent(out) :: k   ! rate coefficients ((m^3/mol)^(n-1)/s)
    real(WP), dimension(:), intent(in) :: M     ! third-body concentrations from get_thirdbodies
    real(WP), intent(in) :: Tloc, Ploc          ! temperature (K), pressure (Pa)
    if (Tloc /= T_rate_cache) then
      call update_rate_cache(Tloc)
    end if
    k(1:i_tb_bwd_end) = k_T_cache(1:i_tb_bwd_end)
  end subroutine get_rate_coefficients

  ! Refresh every rate quantity that depends on the temperature only
  subroutine update_rate_cache(Tloc)
    implicit none
    real(WP), intent(in) :: Tloc
    real(WP) :: T_log, T_inv
    real(WP) :: ln_P0RT
    real(WP), dimension(nS) :: cp_R, h_RT, s_R, g_RT
    real(WP), dimension(n_tb+n_tb_rev) :: ln_k_tb
    T_log = log(Tloc)
    T_inv = 1.0_WP/Tloc
    ln_k_tb(1:n_tb) = ln_A_tb(:) + b_tb(:)*T_log - E_R_tb(:)*T_inv
    ! Reverse rates from detailed balance: ln k_r = ln k_f - ln K_c, with
    ! ln K_c = -sum_i nu_i*g_i/(R*T) + dnu*ln(P_ref/(R*T)) and g/(RT) = h/(RT) - s/R from NASA7
    call fcmech_nasa7(Tloc, cp_R, h_RT, s_R)
    g_RT(:) = h_RT(:) - s_R(:)
    ln_P0RT = log(P_ref*T_inv/Rcst)
    ! 2 O + M <=> O2 + M
    ln_k_tb(2) = ln_k_tb(1) + g_RT(sO2) - 2.0_WP*g_RT(sO) + ln_P0RT
    ! Exponentials (vectorized); signs of negative pre-exponential factors are applied afterwards
    call fcmech_vexp(ln_k_tb, k_T_cache(i_arr_end+1:i_tb_bwd_end))
    T_rate_cache = Tloc
  end subroutine update_rate_cache

  ! Reaction rates w(i) = k(i) * product of reactant concentrations [* M for three-body reactions]
  subroutine get_reaction_rates(w,k,m,c)
    implicit none
    real(WP), dimension(nS), intent(in) :: c   ! species concentrations (mol/m^3)
    real(WP), dimension(nR), intent(in) :: k   ! rate coefficients
    real(WP), dimension(:), intent(in) :: m    ! third-body concentrations from get_thirdbodies
    real(WP), dimension(nR), intent(out) :: w  ! reaction rates (mol/(m^3 s))
    ! 2 O + M => O2 + M  [reversible; reverse in w(2)]
    w(1) = k(1) * c(sO)**2 * m(1)
    ! O2 + M => 2 O + M  [reverse of w(1)]
    w(2) = k(2) * c(sO2) * m(1)
  end subroutine get_reaction_rates

  ! Species production rates cdot(i) = sum_r nu(i,r)*w(r); reversible reactions enter once, as net rates
  subroutine get_production_rates(cdot,w)
    implicit none
    real(WP), dimension(nR), intent(in) :: w      ! reaction rates (mol/(m^3 s))
    real(WP), dimension(nS), intent(out) :: cdot  ! production rates (mol/(m^3 s))
    real(WP), dimension(n_rev) :: wn  ! net rates w(forward) - w(reverse) of the reversible reactions
    wn(:) = w(rev_fwd_w(:)) - w(rev_bwd_w(:))
    cdot(sO2) = wn(1)
    cdot(sO) = - 2.0_WP*wn(1)
    cdot(sN2) = 0.0_WP
  end subroutine get_production_rates

  ! Species destruction rates cdes(i) = sum over the one-directional rates consuming species i of |nu|*w(r)
  ! (>= 0). -cdes(i)/c(i) approximates the diagonal of the chemical Jacobian: the stiffness measure that
  ! bounds the stable time step of an explicit integration of the chemical source terms.
  subroutine get_destruction_rates(cdes,w)
    implicit none
    real(WP), dimension(nR), intent(in) :: w      ! reaction rates (mol/(m^3 s))
    real(WP), dimension(nS), intent(out) :: cdes  ! destruction rates (mol/(m^3 s))
    cdes(sO2) = w(2)
    cdes(sO) = 2.0_WP*w(1)
    cdes(sN2) = 0.0_WP
  end subroutine get_destruction_rates

  ! Molar concentrations c = rho*y/W from mass fractions, ideal gas rho = P*W_mix/(R*T)
  subroutine y2c(y, W_sp, P, T, c)
    implicit none
    real(WP), dimension(nS), intent(in) :: y     ! mass fractions
    real(WP), dimension(nS), intent(in) :: W_sp  ! molar masses (kg/mol)
    real(WP), intent(in) :: P, T                 ! pressure (Pa), temperature (K)
    real(WP), dimension(nS), intent(out) :: c    ! concentrations (mol/m^3)
    real(WP) :: W_mix, rho
    W_mix = 1.0_WP / sum(y(1:nS) / W_sp(1:nS))
    rho = P * W_mix / (Rcst * T)
    c(1:nS) = rho * y(1:nS) / W_sp(1:nS)
  end subroutine y2c

  ! NASA7 polynomials for all species at T: cp/R, h/(RT), s/R (low-T coefficients for T <= T_mid).
  ! Results are cached: repeated calls at the same T (thermo + kinetics in one RHS evaluation) cost a copy.
  subroutine fcmech_nasa7(T, cp_R, h_RT, s_R)
    implicit none
    real(WP), intent(in) :: T
    real(WP), dimension(nS), intent(out) :: cp_R, h_RT, s_R
    real(WP) :: T2, T3, T4, lnT, Tinv
    integer :: i, j
    if (T /= T_nasa_cache) then
      T2 = T*T
      T3 = T2*T
      T4 = T3*T
      lnT = log(T)
      Tinv = 1.0_WP/T
      do i = 1, nS
        if (T <= T_mid(i)) then
          j = 0
        else
          j = 7
        end if
        cp_R_cache(i) = thermo_coeffs(i,j+1) + thermo_coeffs(i,j+2)*T + thermo_coeffs(i,j+3)*T2 &
                      + thermo_coeffs(i,j+4)*T3 + thermo_coeffs(i,j+5)*T4
        h_RT_cache(i) = thermo_coeffs(i,j+1) + 0.5_WP*thermo_coeffs(i,j+2)*T + thermo_coeffs(i,j+3)*T2/3.0_WP &
                      + 0.25_WP*thermo_coeffs(i,j+4)*T3 + 0.2_WP*thermo_coeffs(i,j+5)*T4 + thermo_coeffs(i,j+6)*Tinv
        s_R_cache(i) = thermo_coeffs(i,j+1)*lnT + thermo_coeffs(i,j+2)*T + 0.5_WP*thermo_coeffs(i,j+3)*T2 &
                     + thermo_coeffs(i,j+4)*T3/3.0_WP + 0.25_WP*thermo_coeffs(i,j+5)*T4 + thermo_coeffs(i,j+7)
      end do
      T_nasa_cache = T
    end if
    cp_R(:) = cp_R_cache(:)
    h_RT(:) = h_RT_cache(:)
    s_R(:) = s_R_cache(:)
  end subroutine fcmech_nasa7

  ! Set module arrays Cpsp (J/(mol K)) and hsp (J/mol) at T
  subroutine fcmech_thermodata(T)
    implicit none
    real(WP), intent(in) :: T
    real(WP), dimension(nS) :: cp_R, h_RT, s_R
    call fcmech_nasa7(T, cp_R, h_RT, s_R)
    Cpsp(:) = Rcst * cp_R(:)
    hsp(:) = Rcst * T * h_RT(:)
  end subroutine fcmech_thermodata

  subroutine fcmech_get_thermodata(h,cp,T)
    implicit none
    real(WP), dimension(nS), intent(out) :: h, cp  ! enthalpy (J/mol), heat capacity (J/(mol K))
    real(WP), intent(in) :: T
    call fcmech_thermodata(T)
    h = hsp
    cp = Cpsp
  end subroutine fcmech_get_thermodata

  subroutine fcmech_get_speciesnames(names)
    implicit none
    character(len=*), dimension(nS), intent(out) :: names
    names(1) = 'O2'
    names(2) = 'O'
    names(3) = 'N2'
  end subroutine fcmech_get_speciesnames

  subroutine fcmech_get_atomnames(names)
    implicit none
    character(len=*), dimension(nA), intent(out) :: names
    names(1:nA) = atom_names(1:nA)
  end subroutine fcmech_get_atomnames

  subroutine fcmech_get_atommasses(masses)
    implicit none
    real(WP), dimension(nA), intent(out) :: masses  ! atom molar masses (kg/mol)
    masses(1:nA) = atom_masses(1:nA)
  end subroutine fcmech_get_atommasses

  subroutine fcmech_get_composition(comp)
    implicit none
    integer, dimension(nA,nS), intent(out) :: comp  ! comp(a,s) = count of atom a in species s
    comp(1:nA,1:nS) = comp_matrix(1:nA,1:nS)
  end subroutine fcmech_get_composition

  ! Pure-species viscosity (Pa s), Chapman-Enskog with Lennard-Jones potential
  subroutine fcmech_get_viscosity(mu, T)
    implicit none
    real(WP), dimension(nS), intent(out) :: mu
    real(WP), intent(in) :: T
    integer :: i
    do i = 1, nS
      mu(i) = mucoeff(i)*sqrt(T)/fcmech_omegamu(T*koveps(i))
    end do
  end subroutine fcmech_get_viscosity

  ! Pure-species thermal conductivity (W/(m K)), modified Eucken: lambda = mu*(cp + 1.25*R)/W
  subroutine fcmech_get_conductivity(lambda, T, mu)
    implicit none
    real(WP), dimension(nS), intent(out) :: lambda
    real(WP), intent(in) :: T
    real(WP), dimension(nS), intent(in) :: mu  ! viscosity from fcmech_get_viscosity
    real(WP), dimension(nS) :: cp_R, h_RT, s_R
    call fcmech_nasa7(T, cp_R, h_RT, s_R)
    lambda(:) = mu(:) * Rcst * (cp_R(:) + 1.25_WP) / W_sp(:)
  end subroutine fcmech_get_conductivity

  ! Inverse binary diffusion coefficients 1/D_ij (s/m^2), Chapman-Enskog
  subroutine fcmech_get_invDij(invDij, T, P)
    implicit none
    real(WP), dimension(nS,nS), intent(out) :: invDij
    real(WP), intent(in) :: T, P  ! temperature (K), pressure (Pa)
    real(WP) :: TPterm
    integer :: i, j
    TPterm = P/(T*sqrt(T))
    do i = 1, nS
      do j = 1, i-1
        invDij(i,j) = TPterm*fcmech_omegaD(T*Ocoeffs(i,j))/Dcoeffs(i,j)
        invDij(j,i) = invDij(i,j)
      end do
      invDij(i,i) = 0.0_WP
    end do
  end subroutine fcmech_get_invDij

  ! Mass-based production rates dY_i/dt (1/s) at (P,T,Y): ydot_i = W_i*cdot_i/rho
  subroutine fcmech_get_ydot(P, T, Y, ydot)
    implicit none
    real(WP), intent(in) :: P, T                 ! pressure (Pa), temperature (K)
    real(WP), dimension(nS), intent(in) :: Y     ! mass fractions
    real(WP), dimension(nS), intent(out) :: ydot
    real(WP), dimension(nS) :: c, wdot
    real(WP), dimension(nR) :: k, w
    real(WP), dimension(n_m) :: M
    real(WP) :: W_mix, rho
    call y2c(Y, W_sp, P, T, c)
    call get_thirdbodies(M, c)
    call get_rate_coefficients(k, M, T, P)
    call get_reaction_rates(w, k, M, c)
    call get_production_rates(wdot, w)
    W_mix = 1.0_WP / sum(Y(1:nS) / W_sp(1:nS))
    rho = P * W_mix / (Rcst * T)
    ydot(1:nS) = W_sp(1:nS) * wdot(1:nS) / rho
  end subroutine fcmech_get_ydot

  ! Mass-based production and destruction rates (1/s) at (P,T,Y): ydot_i = W_i*cdot_i/rho and
  ! ddot_i = W_i*cdes_i/rho >= 0; ddot_i/Y_i is the destruction-rate coefficient of species i (explicit
  ! time-step control). Same rate evaluation as fcmech_get_ydot, one extra pass over the reactions.
  subroutine fcmech_get_ydot_ddot(P, T, Y, ydot, ddot)
    implicit none
    real(WP), intent(in) :: P, T                 ! pressure (Pa), temperature (K)
    real(WP), dimension(nS), intent(in) :: Y     ! mass fractions
    real(WP), dimension(nS), intent(out) :: ydot, ddot
    real(WP), dimension(nS) :: c, wdot, wdes
    real(WP), dimension(nR) :: k, w
    real(WP), dimension(n_m) :: M
    real(WP) :: W_mix, rho
    call y2c(Y, W_sp, P, T, c)
    call get_thirdbodies(M, c)
    call get_rate_coefficients(k, M, T, P)
    call get_reaction_rates(w, k, M, c)
    call get_production_rates(wdot, w)
    call get_destruction_rates(wdes, w)
    W_mix = 1.0_WP / sum(Y(1:nS) / W_sp(1:nS))
    rho = P * W_mix / (Rcst * T)
    ydot(1:nS) = W_sp(1:nS) * wdot(1:nS) / rho
    ddot(1:nS) = W_sp(1:nS) * wdes(1:nS) / rho
  end subroutine fcmech_get_ydot_ddot

end module fcmech
