title: NGA2
description: High-performance multiphysics CFD framework
url: "https://desjardi.github.io"
baseurl: "/NGA2"
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

header_pages:
  - index.md
