#!/usr/bin/env python3
"""
Convert chem_data_fc.f90 (or fcmech.f90) to Cantera YAML mechanism format.

Usage: python nga2yaml.py <chem_data_fc.f90> [output.yaml]
       Default output: mechanism.yaml (if not specified)

Requires chem_data_reactions.txt (or fcmech_reactions.txt) in the same directory (generated by yaml2nga).
"""

import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: PyYAML required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

try:
    import numpy as np
except ImportError:
    print("Error: NumPy required. Install with: pip install numpy", file=sys.stderr)
    sys.exit(1)

# Constants
R_UNIV = 8.314462618  # J/(mol·K)
CAL_TO_J = 4.184  # cal to J
CM_TO_M3_FACTOR = 1e-6  # per power of concentration


def _to_native(obj):
    """Convert numpy types to native Python for YAML serialization."""
    if isinstance(obj, (np.floating, np.integer)):
        return float(obj) if isinstance(obj, np.floating) else int(obj)
    if isinstance(obj, np.ndarray):
        return [_to_native(x) for x in obj.tolist()]
    if isinstance(obj, dict):
        return {k: _to_native(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_to_native(x) for x in obj]
    return obj


def _fmt_thermo(x):
    """Format thermo coefficient like h2o2 (8 sig figs, no trailing zeros)."""
    if x == 0:
        return "0.0"
    s = f"{x:.8g}"
    return s.replace("e+0", "e+").replace("e-0", "e-") if "e" in s else s


def _fmt_transport(x):
    """Format transport value like h2o2 (2-3 decimals)."""
    if 0.01 <= abs(x) <= 1000:
        s = f"{x:.3f}".rstrip("0").rstrip(".")
        return s + ".0" if s and "." not in s else (s if s else "0")
    return f"{x:.4g}"


def _fmt_rate(x):
    """Format rate constant like h2o2 (compact)."""
    if x == 0:
        return "0.0"
    if abs(x) >= 1e10 or (abs(x) < 1e-4 and x != 0):
        s = f"{x:.4e}"
        return s.replace("e+0", "e+").replace("e-0", "e-")
    if abs(x) == abs(int(x)) and x == int(x):
        return str(int(x))
    s = f"{x:.6g}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s if s else "0"


def _write_yaml_h2o2_style(out_path, data):
    """Write YAML in h2o2-style format (inline for compact structures, rounded numbers)."""
    lines = []
    lines.append(f"description: {data['description']}")
    lines.append(f"generator: {data['generator']}")
    u = data["units"]
    lines.append(f"units: {{length: {u['length']}, time: {u['time']}, quantity: {u['quantity']}, activation-energy: {u['activation-energy']}}}")
    lines.append("")
    lines.append("phases:")
    for phase in data["phases"]:
        lines.append(f"- name: {phase['name']}")
        lines.append(f"  thermo: {phase['thermo']}")
        lines.append(f"  elements: [{', '.join(phase['elements'])}]")
        lines.append(f"  species: [{', '.join(phase['species'])}]")
        lines.append(f"  kinetics: {phase['kinetics']}")
        lines.append(f"  transport: {phase['transport']}")
        st = phase["state"]
        lines.append(f"  state: {{T: {st['T']}, P: {st['P']}}}")
    lines.append("")
    lines.append("species:")
    for sp in data["species"]:
        lines.append(f"- name: {sp['name']}")
        comp = sp.get("composition", {})
        items = ", ".join(f"{a}: {b}" for a, b in comp.items())
        lines.append(f"  composition: {{{items}}}")
        th = sp.get("thermo", {})
        lines.append("  thermo:")
        lines.append(f"    model: {th.get('model', 'NASA7')}")
        tr = th.get("temperature-ranges", [200, 1000, 3500])
        lines.append(f"    temperature-ranges: [{tr[0]}, {tr[1]}, {tr[2]}]")
        lines.append("    data:")
        for row in th.get("data", [[2.5] * 7, [2.5] * 7]):
            v = [_fmt_thermo(x) for x in row]
            lines.append(f"    - [{', '.join(v[:5])},")
            lines.append(f"      {', '.join(v[5:])}]")
        trans = sp.get("transport", {})
        lines.append("  transport:")
        lines.append(f"    model: {trans.get('model', 'gas')}")
        lines.append(f"    geometry: {trans.get('geometry', 'linear')}")
        lines.append(f"    well-depth: {_fmt_transport(trans.get('well-depth', 100))}")
        lines.append(f"    diameter: {_fmt_transport(trans.get('diameter', 3))}")
    lines.append("")
    lines.append("reactions:")
    for r in data["reactions"]:
        lines.append(f"- equation: {r.get('equation', '')}")
        if r.get("duplicate"):
            lines.append("  duplicate: true")
        if "type" in r:
            lines.append(f"  type: {r['type']}")
        if "rate-constant" in r:
            rc = r["rate-constant"]
            lines.append(f"  rate-constant: {{A: {_fmt_rate(rc['A'])}, b: {_fmt_rate(rc['b'])}, Ea: {_fmt_rate(rc['Ea'])}}}")
        if "low-P-rate-constant" in r:
            lrc = r["low-P-rate-constant"]
            lines.append(f"  low-P-rate-constant: {{A: {_fmt_rate(lrc['A'])}, b: {_fmt_rate(lrc['b'])}, Ea: {_fmt_rate(lrc['Ea'])}}}")
        if "high-P-rate-constant" in r:
            hrc = r["high-P-rate-constant"]
            lines.append(f"  high-P-rate-constant: {{A: {_fmt_rate(hrc['A'])}, b: {_fmt_rate(hrc['b'])}, Ea: {_fmt_rate(hrc['Ea'])}}}")
        if "Troe" in r:
            t = r["Troe"]
            lines.append(f"  Troe: {{A: {_fmt_transport(t['A'])}, T3: {_fmt_transport(t['T3'])}, T1: {_fmt_transport(t['T1'])}, T2: {_fmt_transport(t['T2'])}}}")
        if "efficiencies" in r:
            eff = r["efficiencies"]
            items = ", ".join(f"{a}: {_fmt_transport(b)}" for a, b in eff.items())
            lines.append(f"  efficiencies: {{{items}}}")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")


def si_to_cgs_A(A_si, n_reactants):
    """Convert pre-exponential A from SI (m, mol) to YAML cgs (cm, mol)."""
    return A_si / (CM_TO_M3_FACTOR ** (n_reactants - 1))


def parse_f90_real(s):
    """Parse Fortran real literal like 2.015880e-03_WP."""
    s = s.strip().replace("_WP", "").replace("d", "e").replace("D", "e")
    return float(s)


def parse_f90_array(content, name, ndim=1, n_override=None):
    """Extract array values from Fortran source. Returns list or 2D array.
    n_override: dict like {'nS': 10, 'nA': 4} to resolve dimension(nS) etc."""
    # Match "dimension(N) :: name = (/ &" or "= [ &" (Fortran array constructors)
    pat_1d_num = re.compile(
        rf"dimension\s*\(\s*(\d+)\s*\)\s*::\s*{re.escape(name)}\s*=\s*(?:\(\s*/\s*&|\[\s*&)",
        re.IGNORECASE
    )
    pat_1d_var = re.compile(
        rf"dimension\s*\(\s*(\w+)\s*\)\s*::\s*{re.escape(name)}\s*=\s*(?:\(\s*/\s*&|\[\s*&)",
        re.IGNORECASE
    )
    pat_2d = re.compile(
        rf"dimension\s*\(\s*(\d+|\w+)\s*,\s*(\d+|\w+)\s*\)\s*::\s*{re.escape(name)}\s*=\s*reshape",
        re.IGNORECASE
    )
    # Collect values: numbers with optional _WP, separated by comma
    num_pat = re.compile(r"([+-]?\d+\.?\d*[eEdD][+-]?\d+|[+-]?\d+\.\d*|[+-]?\d+)")

    def resolve_size(s):
        if s.isdigit():
            return int(s)
        return n_override.get(s, 0) if n_override else 0

    m = pat_1d_num.search(content)
    if not m:
        m = pat_1d_var.search(content)
    if m:
        n = resolve_size(m.group(1))
        if n == 0:
            n = 999
        start = m.end()
        # Find closing /)
        end = content.find("/)", start)
        if end == -1:
            end = content.find("]", start)
        if end == -1:
            return []
        chunk = content[start:end]
        chunk = re.sub(r"!.*", "", chunk)
        vals = [parse_f90_real(x) for x in num_pat.findall(chunk)]
        return vals[:n] if len(vals) >= n else vals

    m = pat_2d.search(content)
    if m:
        nrows, ncols = resolve_size(m.group(1)), resolve_size(m.group(2))
        start = m.end()
        end = content.find("]", start)
        if end == -1:
            end = content.find("/)", start)
        if end == -1:
            return np.zeros((nrows, ncols))
        chunk = content[start:end]
        chunk = re.sub(r"!.*", "", chunk)
        vals = [parse_f90_real(x) for x in num_pat.findall(chunk)]
        if len(vals) >= nrows * ncols:
            arr = np.array(vals[: nrows * ncols])
            return arr.reshape((nrows, ncols), order="F")
        return np.zeros((nrows, ncols))

    return [] if ndim == 1 else np.array([])


def parse_int_param(content, name):
    """Extract integer parameter value. Handles both ':: name = N' and ', name = N' (comma-separated)."""
    m = re.search(rf"integer\s*,\s*parameter\s*::\s*{re.escape(name)}\s*=\s*(\d+)", content, re.I)
    if not m:
        m = re.search(rf",\s*{re.escape(name)}\s*=\s*(\d+)", content, re.I)
    return int(m.group(1)) if m else 0


def parse_species_from_f90(content):
    """Extract species names. Prefer fcmech_get_speciesnames (canonical, e.g. CH2(S));
    fallback to sXXX = N parameter lines (yields CH2S from sCH2S)."""
    # Try fcmech_get_speciesnames first (has correct names like CH2(S), AR)
    m = re.search(r"subroutine\s+fcmech_get_speciesnames\s*\(.*?\)(.*?)end\s+subroutine", content, re.DOTALL | re.I)
    if m:
        chunk = m.group(1)
        names = re.findall(r"names\s*\(\s*(\d+)\s*\)\s*=\s*['\"]([^'\"]+)['\"]", chunk, re.I)
        if names:
            by_idx = {int(idx): n.strip() for idx, n in names}
            nS = parse_int_param(content, "nS")
            result = [by_idx.get(i + 1, f"SP{i+1}") for i in range(nS)]
            if all(s != f"SP{i+1}" for i, s in enumerate(result) if i < 5):
                return result
    # Fallback: sXXX = N (CH2S from sCH2S; map CH2S -> CH2(S) for Cantera)
    species = []
    for m in re.finditer(r"integer\s*,\s*parameter\s*::\s*(s\w+)\s*=\s*(\d+)", content, re.I):
        pname, idx = m.group(1), int(m.group(2))
        if pname.startswith("s") and len(pname) > 1:
            sp = pname[1:].replace("_", "")
            if sp.upper() not in ("ARR", "TB", "FO", "PLOG"):
                if sp.upper() == "CH2S":
                    sp = "CH2(S)"  # Cantera uses CH2(S), not CH2S
                species.append((idx, sp))
    species.sort(key=lambda x: x[0])
    return [sp for _, sp in species]


def parse_atom_names(content):
    """Extract atom names from character array."""
    m = re.search(r"atom_names\s*=\s*\(\s*/\s*&(.*?)\s*/\s*\)", content, re.DOTALL | re.I)
    if not m:
        return []
    chunk = m.group(1)
    names = re.findall(r"'([^']{1,2})'", chunk)
    return [n.strip() for n in names]


def load_fcmech(path):
    """Load and parse chem_data_fc.f90 or fcmech.f90."""
    with open(path) as f:
        content = f.read()

    nS = parse_int_param(content, "nS")
    nR = parse_int_param(content, "nR")
    nA = parse_int_param(content, "nA")
    n_ov = {"nS": nS, "nR": nR, "nA": nA, "n_arr": parse_int_param(content, "n_arr"),
            "n_tb": parse_int_param(content, "n_tb"), "n_fo": parse_int_param(content, "n_fo")}
    n_arr = parse_int_param(content, "n_arr")
    n_tb = parse_int_param(content, "n_tb")
    n_fo = parse_int_param(content, "n_fo")
    n_plog = parse_int_param(content, "n_plog")
    n_plog_pts = parse_int_param(content, "n_plog_pts")

    i_arr_end = parse_int_param(content, "i_arr_end")
    i_tb_end = parse_int_param(content, "i_tb_end")
    i_tb_bwd_end = parse_int_param(content, "i_tb_bwd_end")
    i_fo_end = parse_int_param(content, "i_fo_end")
    i_fo_bwd_end = parse_int_param(content, "i_fo_bwd_end")
    i_plog_start = parse_int_param(content, "i_plog_start")

    species_names = parse_species_from_f90(content)
    if len(species_names) != nS:
        species_names = [f"SP{i+1}" for i in range(nS)]

    W_sp = parse_f90_array(content, "W_sp", n_override=n_ov)
    koveps = parse_f90_array(content, "koveps", n_override=n_ov)
    mucoeff = parse_f90_array(content, "mucoeff", n_override=n_ov)
    T_mid = parse_f90_array(content, "T_mid", n_override=n_ov)
    thermo_coeffs = parse_f90_array(content, "thermo_coeffs", n_override=n_ov)
    atom_names = parse_atom_names(content)
    atom_masses = parse_f90_array(content, "atom_masses", n_override=n_ov)
    comp_matrix = parse_f90_array(content, "comp_matrix", n_override=n_ov)
    # comp_matrix may be reshape((/ comp_matrix_c1, comp_matrix_c2 /), ...) - parse parts separately
    if (isinstance(comp_matrix, np.ndarray) and comp_matrix.size > 0 and
            np.all(comp_matrix == 0) and nA * nS > 0):
        c1 = parse_f90_array(content, "comp_matrix_c1", n_override=n_ov)
        c2 = parse_f90_array(content, "comp_matrix_c2", n_override=n_ov)
        if c1 and c2 and len(c1) + len(c2) >= nA * nS:
            c1 = np.array(c1) if isinstance(c1, list) else c1
            c2 = np.array(c2) if isinstance(c2, list) else c2
            vals = np.concatenate([np.atleast_1d(c1).ravel(), np.atleast_1d(c2).ravel()])
            comp_matrix = vals[: nA * nS].reshape((nA, nS), order="F")

    # thermo_coeffs may be reshape([thermo_coeffs_c1, ..., thermo_coeffs_c5], ...) - parse parts
    if (isinstance(thermo_coeffs, np.ndarray) and thermo_coeffs.size > 0 and
            np.all(thermo_coeffs == 0) and nS * 14 > 0):
        tc_parts = []
        for k in range(1, 6):
            pk = parse_f90_array(content, f"thermo_coeffs_c{k}", n_override=n_ov)
            if pk:
                tc_parts.append(np.atleast_1d(np.array(pk) if isinstance(pk, list) else pk).ravel())
        if tc_parts and sum(len(p) for p in tc_parts) >= nS * 14:
            vals = np.concatenate(tc_parts)[: nS * 14]
            thermo_coeffs = vals.reshape((nS, 14), order="F")

    ln_A_arr = parse_f90_array(content, "ln_A_arr", n_override=n_ov)
    b_arr = parse_f90_array(content, "b_arr", n_override=n_ov)
    E_R_arr = parse_f90_array(content, "E_R_arr", n_override=n_ov)

    ln_A_tb = parse_f90_array(content, "ln_A_tb", n_override=n_ov)
    b_tb = parse_f90_array(content, "b_tb", n_override=n_ov)
    E_R_tb = parse_f90_array(content, "E_R_tb", n_override=n_ov)
    ln_A_tb_b = parse_f90_array(content, "ln_A_tb_b", n_override=n_ov)
    b_tb_b = parse_f90_array(content, "b_tb_b", n_override=n_ov)
    E_R_tb_b = parse_f90_array(content, "E_R_tb_b", n_override=n_ov)
    tb_rev_idx = parse_f90_array(content, "tb_rev_idx", n_override=n_ov)

    ln_A0_fo = parse_f90_array(content, "ln_A0_fo", n_override=n_ov)
    b0_fo = parse_f90_array(content, "b0_fo", n_override=n_ov)
    E_R0_fo = parse_f90_array(content, "E_R0_fo", n_override=n_ov)
    ln_Ainf_fo = parse_f90_array(content, "ln_Ainf_fo", n_override=n_ov)
    binf_fo = parse_f90_array(content, "binf_fo", n_override=n_ov)
    E_Rinf_fo = parse_f90_array(content, "E_Rinf_fo", n_override=n_ov)
    Troe_a = parse_f90_array(content, "Troe_a", n_override=n_ov)
    Troe_T3 = parse_f90_array(content, "Troe_T3", n_override=n_ov)
    Troe_T1 = parse_f90_array(content, "Troe_T1", n_override=n_ov)
    Troe_T2 = parse_f90_array(content, "Troe_T2", n_override=n_ov)
    ln_A0_b_fo = parse_f90_array(content, "ln_A0_b_fo", n_override=n_ov)
    b0_b_fo = parse_f90_array(content, "b0_b_fo", n_override=n_ov)
    E_R0_b_fo = parse_f90_array(content, "E_R0_b_fo", n_override=n_ov)
    ln_Ainf_b_fo = parse_f90_array(content, "ln_Ainf_b_fo", n_override=n_ov)
    binf_b_fo = parse_f90_array(content, "binf_b_fo", n_override=n_ov)
    E_Rinf_b_fo = parse_f90_array(content, "E_Rinf_b_fo", n_override=n_ov)
    fo_rev_idx = parse_f90_array(content, "fo_rev_idx", n_override=n_ov)

    n_eff = parse_int_param(content, "n_eff")
    n_ov["n_eff"] = n_eff
    n_m = n_tb + n_fo
    eff_species_idx = parse_f90_array(content, "eff_species_idx", n_override=n_ov)
    eff_matrix_reduced = parse_f90_array(content, "eff_matrix_reduced", n_override=n_ov)
    # eff_matrix_reduced may be reshape([ eff_matrix_reduced_c1, eff_matrix_reduced_c2, ... ], ...) - parse parts
    if (isinstance(eff_matrix_reduced, np.ndarray) and eff_matrix_reduced.size > 0 and
            np.all(eff_matrix_reduced == 0) and n_m * n_eff > 0):
        emr_parts = []
        for k in range(1, 10):
            pk = parse_f90_array(content, f"eff_matrix_reduced_c{k}", n_override=n_ov)
            if pk:
                emr_parts.append(np.atleast_1d(np.array(pk) if isinstance(pk, list) else pk).ravel())
            else:
                break
        if emr_parts and sum(len(p) for p in emr_parts) >= n_m * n_eff:
            vals = np.concatenate(emr_parts)[: n_m * n_eff]
            eff_matrix_reduced = vals.reshape((n_m, n_eff), order="F")

    P_plog = parse_f90_array(content, "P_plog", n_override=n_ov)
    ln_A_plog = parse_f90_array(content, "ln_A_plog", n_override=n_ov)
    b_plog = parse_f90_array(content, "b_plog", n_override=n_ov)
    E_R_plog = parse_f90_array(content, "E_R_plog", n_override=n_ov)
    plog_reac_start = parse_f90_array(content, "plog_reac_start", n_override=n_ov)
    plog_reac_len = parse_f90_array(content, "plog_reac_len", n_override=n_ov)

    return {
        "nS": nS,
        "nR": nR,
        "nA": nA,
        "species_names": species_names,
        "W_sp": np.array(W_sp) if W_sp else np.zeros(nS),
        "koveps": np.array(koveps) if koveps else np.ones(nS) * 0.01,
        "mucoeff": np.array(mucoeff) if mucoeff else np.ones(nS) * 1e-6,
        "T_mid": np.array(T_mid) if T_mid else np.ones(nS) * 1000.0,
        "thermo_coeffs": np.array(thermo_coeffs) if isinstance(thermo_coeffs, np.ndarray) else np.zeros((nS, 14)),
        "atom_names": atom_names or [],
        "atom_masses": np.array(atom_masses) if atom_masses else np.zeros(nA),
        "comp_matrix": np.array(comp_matrix) if isinstance(comp_matrix, np.ndarray) else np.zeros((nA, nS)),
        "ln_A_arr": np.array(ln_A_arr) if ln_A_arr else np.array([]),
        "b_arr": np.array(b_arr) if b_arr else np.array([]),
        "E_R_arr": np.array(E_R_arr) if E_R_arr else np.array([]),
        "n_arr": n_arr,
        "n_tb": n_tb,
        "n_fo": n_fo,
        "n_plog": n_plog,
        "i_arr_end": i_arr_end,
        "i_tb_end": i_tb_end,
        "i_tb_bwd_end": i_tb_bwd_end,
        "i_fo_end": i_fo_end,
        "i_fo_bwd_end": i_fo_bwd_end,
        "i_plog_start": i_plog_start,
        "ln_A_tb": np.array(ln_A_tb) if ln_A_tb else np.array([]),
        "b_tb": np.array(b_tb) if b_tb else np.array([]),
        "E_R_tb": np.array(E_R_tb) if E_R_tb else np.array([]),
        "ln_A_tb_b": np.array(ln_A_tb_b) if ln_A_tb_b else np.array([]),
        "b_tb_b": np.array(b_tb_b) if b_tb_b else np.array([]),
        "E_R_tb_b": np.array(E_R_tb_b) if E_R_tb_b else np.array([]),
        "tb_rev_idx": np.array(tb_rev_idx) if tb_rev_idx else np.array([]),
        "ln_A0_fo": np.array(ln_A0_fo) if ln_A0_fo else np.array([]),
        "b0_fo": np.array(b0_fo) if b0_fo else np.array([]),
        "E_R0_fo": np.array(E_R0_fo) if E_R0_fo else np.array([]),
        "ln_Ainf_fo": np.array(ln_Ainf_fo) if ln_Ainf_fo else np.array([]),
        "binf_fo": np.array(binf_fo) if binf_fo else np.array([]),
        "E_Rinf_fo": np.array(E_Rinf_fo) if E_Rinf_fo else np.array([]),
        "Troe_a": np.array(Troe_a) if Troe_a else np.array([]),
        "Troe_T3": np.array(Troe_T3) if Troe_T3 else np.array([]),
        "Troe_T1": np.array(Troe_T1) if Troe_T1 else np.array([]),
        "Troe_T2": np.array(Troe_T2) if Troe_T2 else np.array([]),
        "ln_A0_b_fo": np.array(ln_A0_b_fo) if ln_A0_b_fo else np.array([]),
        "b0_b_fo": np.array(b0_b_fo) if b0_b_fo else np.array([]),
        "E_R0_b_fo": np.array(E_R0_b_fo) if E_R0_b_fo else np.array([]),
        "ln_Ainf_b_fo": np.array(ln_Ainf_b_fo) if ln_Ainf_b_fo else np.array([]),
        "binf_b_fo": np.array(binf_b_fo) if binf_b_fo else np.array([]),
        "E_Rinf_b_fo": np.array(E_Rinf_b_fo) if E_Rinf_b_fo else np.array([]),
        "fo_rev_idx": np.array(fo_rev_idx) if fo_rev_idx else np.array([]),
        "n_eff": n_eff,
        "eff_species_idx": np.array(eff_species_idx) if eff_species_idx else np.array([]),
        "eff_matrix_reduced": np.array(eff_matrix_reduced) if isinstance(eff_matrix_reduced, np.ndarray) else np.array([]),
        "P_plog": np.array(P_plog) if P_plog else np.array([]),
        "ln_A_plog": np.array(ln_A_plog) if ln_A_plog else np.array([]),
        "b_plog": np.array(b_plog) if b_plog else np.array([]),
        "E_R_plog": np.array(E_R_plog) if E_R_plog else np.array([]),
        "plog_reac_start": np.array(plog_reac_start) if plog_reac_start else np.array([]),
        "plog_reac_len": np.array(plog_reac_len) if plog_reac_len else np.array([]),
    }


def parse_reactions_file(path):
    """Parse chem_data_reactions.txt or fcmech_reactions.txt. Returns list of (w_idx, equation, label)."""
    if not path.exists():
        return []
    entries = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("fcmech") or line.startswith("chem_data") or line.startswith("=") or line.startswith("-"):
                continue
            m = re.match(r"^\s*(\d+)\s+(.+?)(?:\s+#\s*(.+))?$", line)
            if m:
                w_idx = int(m.group(1))
                eq = m.group(2).strip()
                label = (m.group(3).strip() if m.group(3) else "").lstrip("# ").strip()
                entries.append((w_idx, eq, label))
    return entries


def parse_equation(eq):
    """Parse reaction equation to (left, right, rev). Left/right are lists of (species, coeff)."""
    eq = eq.split("#")[0].strip()
    rev = "<=>" in eq
    if rev:
        left, right = eq.split("<=>")
    else:
        left, right = eq.split("=>") if "=>" in eq else (eq, "")
    left, right = left.strip(), right.strip()

    def parse_side(s):
        if not s:
            return []
        s = re.sub(r"\s*\(\+?\s*M\s*\)\s*", " ", s)
        terms = re.split(r"\s+\+\s+", s)
        out = []
        for t in terms:
            t = t.strip()
            if not t:
                continue
            m = re.match(r"^(\d*)\s*([A-Za-z0-9_()\-]+)\s*$", t)
            if m:
                coeff = int(m.group(1)) if m.group(1) else 1
                sp = m.group(2)
                if sp.upper() != "M":
                    out.append((sp, coeff))
        return out

    return parse_side(left), parse_side(right), rev


def format_side(side, add_m=False):
    """Format side for YAML equation."""
    parts = []
    for sp, c in side:
        if c == 1:
            parts.append(sp)
        else:
            parts.append(f"{c} {sp}")
    s = " + ".join(parts)
    if add_m:
        s = s + " + M" if s else "M"
    return s


def _canonical_side(side):
    """Format side with species sorted for duplicate detection."""
    sorted_side = sorted(side, key=lambda x: x[0])
    return format_side(sorted_side)


def nga2yaml(fcmech_path, output_path, reactions_path=None, act_energy_unit="cal/mol"):
    """Convert chem_data_fc.f90 (or fcmech.f90) to YAML."""
    fcmech_path = Path(fcmech_path)
    output_path = Path(output_path)

    mech = load_fcmech(fcmech_path)

    if reactions_path is None:
        if fcmech_path.stem == "chem_data_fc":
            reactions_path = fcmech_path.parent / "chem_data_reactions.txt"
        else:
            reactions_path = fcmech_path.parent / (fcmech_path.stem + "_reactions.txt")

    rx_entries = parse_reactions_file(reactions_path)
    if not rx_entries:
        print("Warning: No reactions file found. Reactions will be empty.", file=sys.stderr)

    Ea_scale = CAL_TO_J if "cal" in act_energy_unit.lower() else 1.0

    # Build species list for YAML
    species_list = []
    for i, name in enumerate(mech["species_names"]):
        comp = {}
        if mech["nA"] > 0 and mech["comp_matrix"].size > 0:
            for a in range(mech["nA"]):
                cnt = int(mech["comp_matrix"][a, i])
                if cnt != 0:
                    an = mech["atom_names"][a] if a < len(mech["atom_names"]) else f"A{a}"
                    comp[an] = cnt

        low = _to_native(mech["thermo_coeffs"][i, 0:7].tolist()) if mech["thermo_coeffs"].size > 0 else [2.5, 0, 0, 0, 0, 0, 0]
        high = _to_native(mech["thermo_coeffs"][i, 7:14].tolist()) if mech["thermo_coeffs"].size > 0 else [2.5, 0, 0, 0, 0, 0, 0]
        T_mid = float(mech["T_mid"][i]) if mech["T_mid"].size > 0 else 1000.0
        T_low = 200.0
        T_high = 3500.0

        kov = float(mech["koveps"][i])
        well_depth = 1.0 / kov if kov > 0 else 100.0
        M_kg = float(mech["W_sp"][i])
        mucoeff_i = float(mech.get("mucoeff", np.ones(mech["nS"]) * 1e-6)[i])
        d = float(np.sqrt(2.67e-6 * np.sqrt(M_kg * 1000) / mucoeff_i)) if mucoeff_i > 0 else 3.0

        # Fallback for empty composition: use valid element, not name[0] (e.g. AR -> Ar, not A)
        if not comp:
            if name and name.upper() == "AR":
                comp = {"Ar": 1}
            elif name and name.upper() == "N2":
                comp = {"N": 2}
            else:
                comp = {name[0] if name else "X": 1}
        n_atoms = sum(comp.values()) if comp else 1
        if n_atoms == 1:
            geometry = "atom"
        elif n_atoms == 2:
            geometry = "linear"
        else:
            geometry = "nonlinear"
        sp_dict = {
            "name": name,
            "composition": comp,
            "thermo": {
                "model": "NASA7",
                "temperature-ranges": [T_low, T_mid, T_high],
                "data": [low, high],
            },
            "transport": {
                "model": "gas",
                "geometry": geometry,
                "well-depth": float(well_depth),
                "diameter": d,
            },
        }
        species_list.append(sp_dict)

    # Build reactions from rx_entries and fcmech rate params
    i_arr_end = mech["i_arr_end"]
    i_tb_end = mech["i_tb_end"]
    i_tb_bwd_end = mech["i_tb_bwd_end"]
    i_fo_end = mech["i_fo_end"]
    i_fo_bwd_end = mech["i_fo_bwd_end"]
    n_tb = mech["n_tb"]
    n_fo = mech["n_fo"]
    species_names = mech["species_names"]

    w_to_eq = {w: (eq, label) for w, eq, label in rx_entries}

    def _eq_key(left, right, rxn_type="elementary"):
        """Canonical equation key for duplicate detection (species sorted)."""
        lc = _canonical_side(left)
        rc = _canonical_side(right)
        if rxn_type == "three-body":
            return f"{lc} + M => {rc} + M"
        if rxn_type == "falloff":
            return f"{lc} (+M) => {rc} (+M)"
        return f"{lc} => {rc}"

    seen_equations = {}  # key -> count of occurrences

    # fcmech layout: w 1..n_arr_fwd arr forward, n_arr_fwd+1..i_arr_end arr backward,
    # i_arr_end+1..i_tb_end three-body, i_tb_end+1..i_tb_bwd_end tb backward,
    # i_tb_bwd_end+1..i_fo_end falloff, i_fo_end+1..i_fo_bwd_end falloff backward
    n_arr_fwd = (i_arr_end + 1) // 2

    def n_reactants(side):
        return sum(c for _, c in side)

    reactions_yaml = []
    for w_idx, eq, label in rx_entries:
        left, right, rev = parse_equation(eq)
        if w_idx <= i_arr_end:
            if (w_idx - 1) < len(mech["ln_A_arr"]):
                A_si = np.exp(mech["ln_A_arr"][w_idx - 1])
                b = float(mech["b_arr"][w_idx - 1])
                Ea_J = mech["E_R_arr"][w_idx - 1] * R_UNIV
                Ea = Ea_J / Ea_scale
                n_r = n_reactants(left)
                A_cgs = si_to_cgs_A(A_si, n_r)
                key = _eq_key(left, right, "elementary")
                rxn = {
                    "equation": f"{format_side(left)} => {format_side(right)}" + (f"  # {label}" if label else ""),
                    "rate-constant": {"A": float(A_cgs), "b": float(b), "Ea": float(Ea)},
                }
                n = seen_equations.get(key, 0) + 1
                seen_equations[key] = n
                reactions_yaml.append(rxn)
        elif w_idx <= i_tb_end:
            i = w_idx - (i_arr_end + 1)
            if 0 <= i < n_tb:
                A_si = np.exp(mech["ln_A_tb"][i])
                b = float(mech["b_tb"][i])
                Ea_J = mech["E_R_tb"][i] * R_UNIV
                Ea = Ea_J / Ea_scale
                n_left = n_reactants(left)
                A_cgs = si_to_cgs_A(A_si, n_left + 1)  # A+B+M: n=n_left+1
                eff = {}
                if mech["n_eff"] > 0 and mech["eff_matrix_reduced"].size > 0:
                    for j in range(mech["n_eff"]):
                        sp_idx = int(mech["eff_species_idx"][j]) - 1
                        if sp_idx < len(species_names):
                            eff[species_names[sp_idx]] = float(mech["eff_matrix_reduced"][i, j])
                key = _eq_key(left, right, "three-body")
                rxn = {
                    "equation": f"{format_side(left)} + M => {format_side(right)} + M" + (f"  # {label}" if label else ""),
                    "type": "three-body",
                    "rate-constant": {"A": float(A_cgs), "b": float(b), "Ea": float(Ea)},
                }
                if eff:
                    rxn["efficiencies"] = eff
                n = seen_equations.get(key, 0) + 1
                seen_equations[key] = n
                reactions_yaml.append(rxn)
        elif w_idx <= i_tb_bwd_end:
            bwd_slot = w_idx - i_tb_end - 1
            if 0 <= bwd_slot < len(mech["ln_A_tb_b"]):
                # Find forward index: tb_rev_idx[forward_i] = bwd_slot+1 (1-based)
                tb_rev = mech.get("tb_rev_idx")
                forward_i = None
                if tb_rev is not None and len(tb_rev) >= n_tb:
                    for fi in range(n_tb):
                        if int(tb_rev[fi]) == bwd_slot + 1:
                            forward_i = fi
                            break
                if forward_i is None:
                    forward_i = bwd_slot  # fallback when all reversible (bwd_slot == forward_i)
                A_si = np.exp(mech["ln_A_tb_b"][bwd_slot])
                b = float(mech["b_tb_b"][bwd_slot])
                Ea_J = mech["E_R_tb_b"][bwd_slot] * R_UNIV
                Ea = Ea_J / Ea_scale
                n_left_bwd = n_reactants(left)  # e.g. O2+M=>2O: left=[O2], n=2
                A_cgs = si_to_cgs_A(A_si, n_left_bwd + 1)
                eff = {}
                if mech["n_eff"] > 0 and mech["eff_matrix_reduced"].size > 0:
                    for j in range(mech["n_eff"]):
                        sp_idx = int(mech["eff_species_idx"][j]) - 1
                        if sp_idx < len(species_names):
                            eff[species_names[sp_idx]] = float(mech["eff_matrix_reduced"][forward_i, j])
                key = _eq_key(left, right, "three-body")
                rxn = {
                    "equation": f"{format_side(left)} + M => {format_side(right)} + M" + (f"  # {label}" if label else ""),
                    "type": "three-body",
                    "rate-constant": {"A": float(A_cgs), "b": float(b), "Ea": float(Ea)},
                }
                if eff:
                    rxn["efficiencies"] = eff
                n = seen_equations.get(key, 0) + 1
                seen_equations[key] = n
                reactions_yaml.append(rxn)
        elif w_idx <= i_fo_end:
            i = w_idx - i_tb_bwd_end - 1
            if 0 <= i < n_fo:
                A0_si = np.exp(mech["ln_A0_fo"][i])
                b0 = float(mech["b0_fo"][i])
                Ea0_J = mech["E_R0_fo"][i] * R_UNIV
                Ea0 = Ea0_J / Ea_scale
                Ainf_si = np.exp(mech["ln_Ainf_fo"][i])
                binf = float(mech["binf_fo"][i])
                Eainf_J = mech["E_Rinf_fo"][i] * R_UNIV
                Eainf = Eainf_J / Ea_scale
                # Match yaml2nga: n0=n_left+1, ninf=n_left (by reactant stoichiometry)
                n_left = n_reactants(left)
                n0_fo, ninf_fo = n_left + 1, n_left
                A0_cgs = si_to_cgs_A(A0_si, n0_fo)
                Ainf_cgs = si_to_cgs_A(Ainf_si, ninf_fo)
                eff = {}
                if mech["n_eff"] > 0 and mech["eff_matrix_reduced"].size > 0:
                    for j in range(mech["n_eff"]):
                        sp_idx = int(mech["eff_species_idx"][j]) - 1
                        if sp_idx < len(species_names):
                            eff[species_names[sp_idx]] = float(mech["eff_matrix_reduced"][n_tb + i, j])
                key = _eq_key(left, right, "falloff")
                rxn = {
                    "equation": f"{format_side(left)} (+M) => {format_side(right)} (+M)" + (f"  # {label}" if label else ""),
                    "type": "falloff",
                    "low-P-rate-constant": {"A": float(A0_cgs), "b": float(b0), "Ea": float(Ea0)},
                    "high-P-rate-constant": {"A": float(Ainf_cgs), "b": float(binf), "Ea": float(Eainf)},
                    "Troe": {
                        "A": float(mech["Troe_a"][i]),
                        "T3": float(mech["Troe_T3"][i]),
                        "T1": float(mech["Troe_T1"][i]),
                        "T2": float(mech["Troe_T2"][i]),
                    },
                }
                if eff:
                    rxn["efficiencies"] = eff
                n = seen_equations.get(key, 0) + 1
                seen_equations[key] = n
                reactions_yaml.append(rxn)
        elif w_idx <= i_fo_bwd_end:
            j = w_idx - i_fo_end - 1  # backward slot index (0-based)
            if 0 <= j < len(mech["ln_A0_b_fo"]) and mech.get("fo_rev_idx") is not None:
                # Find parent falloff index: fo_rev_idx[fo_i] = j+1 (1-based)
                fo_i = None
                for i in range(n_fo):
                    if int(mech["fo_rev_idx"][i]) == j + 1:
                        fo_i = i
                        break
                if fo_i is not None:
                    A0_b_si = np.exp(mech["ln_A0_b_fo"][j])
                    b0_b = float(mech["b0_b_fo"][j])
                    Ea0_b_J = mech["E_R0_b_fo"][j] * R_UNIV
                    Ea0_b = Ea0_b_J / Ea_scale
                    Ainf_b_si = np.exp(mech["ln_Ainf_b_fo"][j])
                    binf_b = float(mech["binf_b_fo"][j])
                    Eainf_b_J = mech["E_Rinf_b_fo"][j] * R_UNIV
                    Eainf_b = Eainf_b_J / Ea_scale
                    # Reverse falloff: n0=n_left+1, ninf=n_left (by backward reactant stoichiometry)
                    n_left_bwd = n_reactants(left)
                    A0_b_cgs = si_to_cgs_A(A0_b_si, n_left_bwd + 1)
                    Ainf_b_cgs = si_to_cgs_A(Ainf_b_si, n_left_bwd)
                    eff = {}
                    if mech["n_eff"] > 0 and mech["eff_matrix_reduced"].size > 0:
                        for j_eff in range(mech["n_eff"]):
                            sp_idx = int(mech["eff_species_idx"][j_eff]) - 1
                            if sp_idx < len(species_names):
                                eff[species_names[sp_idx]] = float(mech["eff_matrix_reduced"][n_tb + fo_i, j_eff])
                    key = _eq_key(left, right, "falloff")
                    rxn = {
                        "equation": f"{format_side(left)} (+M) => {format_side(right)} (+M)" + (f"  # {label}" if label else ""),
                        "type": "falloff",
                        "low-P-rate-constant": {"A": float(A0_b_cgs), "b": float(b0_b), "Ea": float(Ea0_b)},
                        "high-P-rate-constant": {"A": float(Ainf_b_cgs), "b": float(binf_b), "Ea": float(Eainf_b)},
                        "Troe": {
                            "A": float(mech["Troe_a"][fo_i]),
                            "T3": float(mech["Troe_T3"][fo_i]),
                            "T1": float(mech["Troe_T1"][fo_i]),
                            "T2": float(mech["Troe_T2"][fo_i]),
                        },
                    }
                    if eff:
                        rxn["efficiencies"] = eff
                    n = seen_equations.get(key, 0) + 1
                    seen_equations[key] = n
                    reactions_yaml.append(rxn)
        # ... (other branches append to reactions_yaml)

    # Mark all occurrences of duplicate equations (Cantera requires all to have duplicate: true)
    for r in reactions_yaml:
        eq = r.get("equation", "")
        eq_base = eq.split("  #")[0].strip()
        # Build key from equation string (normalize order for matching)
        if " + M => " in eq_base and " (+M) " not in eq_base:
            rxn_type = "three-body"
        elif " (+M) => " in eq_base:
            rxn_type = "falloff"
        else:
            rxn_type = "elementary"
        # Parse back to left/right for canonical key
        if " => " in eq_base:
            left_s, right_s = eq_base.split(" => ")
            left_s = left_s.replace(" + M", "").replace(" (+M)", "").strip()
            right_s = right_s.replace(" + M", "").replace(" (+M)", "").strip()
            left = []
            for part in left_s.split(" + "):
                part = part.strip()
                if " " in part:
                    c, sp = part.split(None, 1)
                    left.append((sp, int(float(c))))
                else:
                    left.append((part, 1))
            right = []
            for part in right_s.split(" + "):
                part = part.strip()
                if " " in part:
                    c, sp = part.split(None, 1)
                    right.append((sp, int(float(c))))
                else:
                    right.append((part, 1))
            key = _eq_key(left, right, rxn_type)
            if seen_equations.get(key, 0) > 1:
                r["duplicate"] = True

    # Fix composition for species that have no atoms or invalid elements (e.g. AR->Ar not A)
    for sp in species_list:
        nm = sp["name"]
        comp = sp["composition"]
        # AR: element is Ar, not A (Cantera rejects "A" as undefined)
        if nm.upper() == "AR" and ("A" in comp or "Ar" not in comp or not comp):
            sp["composition"] = {"Ar": 1}
        elif not comp or all(v == 0 for v in comp.values()):
            if nm.upper() in ("AR", "N2"):
                sp["composition"] = {"Ar": 1} if nm.upper() == "AR" else {"N": 2}
            elif mech["nA"] > 0 and mech["comp_matrix"].size > 0:
                idx = species_names.index(sp["name"]) if sp["name"] in species_names else 0
                comp = {}
                for a in range(mech["nA"]):
                    cnt = int(mech["comp_matrix"][a, idx])
                    if cnt != 0:
                        an = mech["atom_names"][a] if a < len(mech["atom_names"]) else f"A{a}"
                        comp[an] = cnt
                sp["composition"] = comp if comp else {"X": 1}

    # Recompute geometry from final composition (fix block may have changed it)
    for sp in species_list:
        comp = sp["composition"]
        n_atoms = sum(comp.values()) if comp else 1
        if n_atoms == 1:
            sp["transport"]["geometry"] = "atom"
        elif n_atoms == 2:
            sp["transport"]["geometry"] = "linear"
        else:
            sp["transport"]["geometry"] = "nonlinear"

    # Build output YAML
    elem_list = mech["atom_names"] if mech["atom_names"] else list({e for s in species_list for e in s["composition"]})
    out = {
        "description": f"Converted from {fcmech_path.name} by nga2yaml",
        "generator": "nga2yaml",
        "units": {"length": "cm", "time": "s", "quantity": "mol", "activation-energy": act_energy_unit},
        "phases": [
            {
                "name": "gas",
                "thermo": "ideal-gas",
                "elements": elem_list,
                "species": species_names,
                "kinetics": "gas",
                "transport": "mixture-averaged",
                "state": {"T": 300.0, "P": "1 atm"},
            }
        ],
        "species": species_list,
        "reactions": reactions_yaml,
    }

    _write_yaml_h2o2_style(output_path, out)

    print(f"Wrote {output_path}")
    return output_path


def main():
    parser = argparse.ArgumentParser(description="Convert chem_data_fc.f90 to Cantera YAML mechanism")
    parser.add_argument("fcmech", help="Path to chem_data_fc.f90 (or fcmech.f90)")
    parser.add_argument("output", nargs="?", default="mechanism.yaml", help="Output YAML path (default: mechanism.yaml)")
    parser.add_argument("--reactions", help="Path to reactions file (default: same dir as fcmech)")
    parser.add_argument("--activation-energy", default="cal/mol", help="Activation energy unit (default: cal/mol)")
    args = parser.parse_args()

    nga2yaml(
        args.fcmech,
        args.output,
        reactions_path=Path(args.reactions) if args.reactions else None,
        act_energy_unit=args.activation_energy,
    )


if __name__ == "__main__":
    main()
